### ISSUE TITLE
use-package example should use :after org?

### ISSUE THREAD

**Issue by ghost** [colonelpanic8/org-projectile#56]
I've been trying to use the installation code for use-package from the README. Running that code caused an error related to `(void-variable org--builtin-p)`. I'm on Emacs 28

However, I've ~stolen~ copied very similar code from https://github.com/meatcar/emacs.d#org-projectile and removed some lines to make it minimalistic:

```lisp
  (use-package org-projectile
    :after projectile org
    :straight t
    :config
    (org-projectile-per-project)
    (push (org-projectile-project-todo-entry) org-capture-templates))
```

After running the above, I can use org-projectile just fine! (this is great news to me as consult doesn't have the counsel-projectile-org-capture)

The only major difference here between the two seems to be the `:after projectile org`. Would you say it's worth adding to the README, or this is totally unrelated and it's and accident that it works?

**Comment by IvanMalison** [comment]
sure that seems like a reasonable addition
